spring.application.name=booknest

# DATABASE

spring.datasource.url=jdbc:postgresql://ep-patient-haze-aqz9zc8p.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_K6alXV0RBkfj

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER

server.port=9000

# JWT

jwt.secret=8f3d92k1mxa7qpl0w9zv2b7t5n4r8yx